import { addDoc, collection, getDocs, limit, query } from "firebase/firestore";
import { db } from "./firebaseConfig";

const ingredients = [
{ name: "Cheddar Cheese", image: "🧀", category: "Dairy" },
{ name: "Whole Milk", image: "💯🥛", category: "Dairy" },
{ name: "Low Fat (1-2%) Milk", image: "📉🥛", category: "Dairy" },
{ name: "Skim Milk", image: "0️⃣🥛", category: "Dairy" },
{ name: "Cottage Cheese", image: "🍚", category: "Dairy" },
{ name: "Salted Butter", image: "🧂🧈", category: "Dairy" },
{ name: "Sour Cream", image: "🍚", category: "Dairy" },
{ name: "Heavy Whipping Cream", image: "🏋🥛", category: "Dairy" },
{ name: "Ice Cream", image: "🍨", category: "Dairy" },
{ name: "Whipped Cream", image: "🥣🥛", category: "Dairy" },
{ name: "Mozzarella Cheese", image: "🧀", category: "Dairy" },
{ name: "Greek Yogurt", image: "🥣", category: "Dairy" },
{ name: "Cream Cheese", image: "🥛🧀", category: "Dairy" },
{ name: "Soy Milk", image: "🥛", category: "Dairy Alternative" },
{ name: "Almond Milk", image: "🥛", category: "Dairy Alternative" },
{ name: "Half and Half", image: "🥛", category: "Dairy" },
{ name: "Parmesan Cheese", image: "🧀", category: "Dairy" },
{ name: "Queso", image: "🧀🔥", category: "Dairy" },
{ name: "Unsalted Butter", image: "🧈", category: "Dairy" },
{ name: "Cheese Sauce", image: "🧀🥣", category: "Dairy" },
{ name: "Eggs", image: "🥚", category: "Protein" },
{ name: "Pork", image: "🥩", category: "Protein" },
{ name: "Ground Beef", image: "🥩", category: "Protein" },
{ name: "Bacon", image: "🥓", category: "Protein" },
{ name: "Sausage", image: "🌭", category: "Protein" },
{ name: "Tofu", image: "⬜", category: "Protein" },
{ name: "Chicken", image: "🍗", category: "Protein" },
{ name: "Chicken Broth", image: "🍗🍲", category: "Condiment" },
{ name: "Salmon", image: "🐟", category: "Protein" },
{ name: "Black Beans", image: "🫘", category: "Protein" },
{ name: "Pinto Beans", image: "🫘", category: "Protein" },
{ name: "Oats", image: "🌾", category: "Carb" },
{ name: "Quinoa", image: "🌾", category: "Carb" },
{ name: "Lentils", image: "🫘", category: "Protein" },
{ name: "Steak", image: "🥩", category: "Protein" },
{ name: "Hemp Seeds", image: "🌱", category: "Protein" },
{ name: "Almonds", image: "🌰", category: "Protein" },
{ name: "Peanuts", image: "🥜", category: "Protein" },
{ name: "Peanut Butter", image: "🥜", category: "Protein" },
{ name: "Tempeh", image: "⬜", category: "Protein" },
{ name: "Green Beans", image: "🫛", category: "Vegetable" },
{ name: "Peas", image: "🫛", category: "Vegetable" },
{ name: "Lettuce", image: "🥬", category: "Vegetable" },
{ name: "Kale", image: "🥬", category: "Vegetable" },
{ name: "Spinach", image: "🍃", category: "Vegetable" },
{ name: "Broccoli", image: "🥦", category: "Vegetable" },
{ name: "Brussel Sprouts", image: "🥬", category: "Vegetable" },
{ name: "Asparagus", image: "🥦", category: "Vegetable" },
{ name: "Green Onions", image: "🟢🧅", category: "Vegetable" },
{ name: "Onions", image: "🧅", category: "Vegetable" },
{ name: "Shallots", image: "🧅", category: "Vegetable" },
{ name: "Garlic", image: "🧄", category: "Vegetable" },
{ name: "Carrots", image: "🥕", category: "Vegetable" },
{ name: "Celery", image: "🥬", category: "Vegetable" },
{ name: "Cabbage", image: "🥬", category: "Vegetable" },
{ name: "Corn", image: "🌽", category: "Vegetable" },
{ name: "Cucumber", image: "🥒", category: "Vegetable" },
{ name: "Potato", image: "🥔", category: "Vegetable" },
{ name: "Sweet Potato", image: "🍠", category: "Vegetable" },
{ name: "Uncooked Pasta Noodles", image: "🍝", category: "Carb" },
{ name: "Rice", image: "🍚", category: "Carb" },
{ name: "Vinegar", image: "🍶", category: "Condiment" },
{ name: "Pickle", image: "🥒", category: "Vegetable" },
{ name: "Tomato Sauce", image: "🥫", category: "Condiment" },
{ name: "Ketchup", image: "🥫", category: "Condiment" },
{ name: "Mayonaise", image: "⚪", category: "Condiment" },
{ name: "Mustard", image: "🟡", category: "Condiment" },
{ name: "All Purpose Flour", image: "🌾", category: "Baking" },
{ name: "Sugar", image: "🍚", category: "Baking" },
{ name: "Brown Sugar", image: "🟫", category: "Baking" },
{ name: "Light Brown Sugar", image: "🟫", category: "Baking" },
{ name: "Chocolate Chips", image: "🍫", category: "Baking" },
{ name: "Powdered Sugar", image: "🍚", category: "Baking" },
{ name: "Vegetable Oil", image: "🛢️", category: "Fat" },
{ name: "Vanilla Extract", image: "🫙", category: "Baking" },
{ name: "Cornstarch", image: "🌽", category: "Baking" },
{ name: "Cake Flour", image: "🌾", category: "Baking" },
{ name: "Baking Powder", image: "🧂", category: "Baking" },
{ name: "Baking Soda", image: "🧂", category: "Baking" },
{ name: "Cocoa Powder", image: "🍫", category: "Baking" },
{ name: "Bread", image: "🍞", category: "Carb" },
{ name: "Tomatoes", image: "🍅", category: "Vegetable" },
{ name: "Bell Peppers", image: "🫑", category: "Vegetable" },
{ name: "Strawberry", image: "🍓", category: "Fruit" },
{ name: "Blackberry", image: "🍇🖤", category: "Fruit" },
{ name: "Blueberry", image: "🫐", category: "Fruit" },
{ name: "Grape", image: "🍇", category: "Fruit" },
{ name: "Habanero Pepper", image: "🌶️", category: "Vegetable" },
{ name: "Jalapeno Pepper", image: "🌶️", category: "Vegetable" },
{ name: "Banana", image: "🍌", category: "Fruit" },
{ name: "Apple", image: "🍎", category: "Fruit" },
{ name: "Orange", image: "🍊", category: "Fruit" },
{ name: "Mango", image: "🥭", category: "Fruit" },
{ name: "Pineapple", image: "🍍", category: "Fruit" },
{ name: "Passion Fruit", image: "🍈", category: "Fruit" },
{ name: "Dragon Fruit", image: "🐉🍎", category: "Fruit" },
{ name: "Raisin", image: "🍇", category: "Fruit" },
{ name: "Lemon", image: "🍋", category: "Fruit" },
{ name: "Lime", image: "🍋‍🟩", category: "Fruit" },
{ name: "Kiwi", image: "🥝", category: "Fruit" }
];

export const seedIngredients = async () => {
  const colRef = collection(db, "ingredients");
  
  // Check if we already have data so we don't duplicate
  const snapshot = await getDocs(query(colRef, limit(1)));
  if (!snapshot.empty) {
    console.log("Ingredients already seeded!");
    return;
  }

  for (const item of ingredients) {
    await addDoc(colRef, item);
  }
  console.log("Database seeded successfully! 🎉");
};